import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
  RedirectToSignIn
} from '@clerk/nextjs';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "YunexTraffic",
  description: "Generated by create next app",
};

const clerkPubKey = 'pk_test_cGxlYXNpbmctbW9uc3Rlci0xNi5jbGVyay5hY2NvdW50cy5kZXYk'; // Aquí añades tu clave pública de Clerk.

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={clerkPubKey}>
      <html lang="en">
        <body>
          <SignedIn>
            {children}  {/* Aquí el contenido de tu aplicación solo es visible si el usuario está autenticado */}
          </SignedIn>
          <SignedOut>
            {/* Redirigir a la página de inicio de sesión si no está autenticado */}
            <RedirectToSignIn 
              signInFallbackRedirectUrl="/reporte-de-hora"  // Página de destino después de iniciar sesión
              signUpFallbackRedirectUrl="/reporte-de-hora"  // Página de destino después de registrarse
            />
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
